import {Nunito, Nunito_Sans} from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});


const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={clsx(nunito.variable, nunitoSans.variable)}>

      
      <body
        // className={`${AxiformaReg.variable} ${AxiformaMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
