import localFont from "next/font/local";
import "./globals.css";


const AxiformaMono = localFont({
  src: [
    {
      path: '../../public/fonts/Axiforma-Regular.woff',
      weight: "400"
    }
  ],
  variable: '--font-Axiforma'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${AxiformaMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
