import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Axiforma-Regular.woff",
  variable: "--font-geist-sans",
  weight: "100 400 500 600 700 800 900",
});
const geistMono = localFont({
  src: "./fonts/Axiforma-Regular.woff2",
  variable: "--font-geist-mono",
  weight: "100 400 500 600 700 800 900",
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
